### ISSUE TITLE
opkg builds

### ISSUE THREAD

**Issue by jacksondm33** [robotpy/robotpy-pathfinder#6]
There are currently no opkg builds for pathfinder. I can't find any information as to why.

**Comment by virtuald** [comment]
I didn't realize people were still using it? It's recommended to use the new WPILib trajectory stuff, it's a lot better in many ways.

**Comment by jacksondm33** [comment]
Oh, ok. I should really stay up to date on the things wpilib is adding. Thanks for the quick response.

**Comment by virtuald** [comment]
I just uploaded an opkg build for it, but I highly recommend using the new WPILib trajectory stuff instead.

https://docs.wpilib.org/en/latest/docs/software/advanced-control/trajectories/index.html . All of the features mentioned are supported in RobotPy for 2020.
